// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAchi_ambriwAhWAeVIf6aJ54_tAdPvvHs',
    appId: '1:15883659596:web:4dbdd1da04bdfdc81e07e9',
    messagingSenderId: '15883659596',
    projectId: 'state-b9713',
    authDomain: 'state-b9713.firebaseapp.com',
    storageBucket: 'state-b9713.appspot.com',
    measurementId: 'G-XJBCC9NB8D',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBY4KcYco3kNfVNQrCPsrkwZPSiqHctPvo',
    appId: '1:15883659596:android:ed2448f70feba0a11e07e9',
    messagingSenderId: '15883659596',
    projectId: 'state-b9713',
    storageBucket: 'state-b9713.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDNP6h0uDqrOvhILn7GM6nSa4OyM1DKfbA',
    appId: '1:15883659596:ios:db7db5c7490107cc1e07e9',
    messagingSenderId: '15883659596',
    projectId: 'state-b9713',
    storageBucket: 'state-b9713.appspot.com',
    iosBundleId: 'com.example.app',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDNP6h0uDqrOvhILn7GM6nSa4OyM1DKfbA',
    appId: '1:15883659596:ios:db7db5c7490107cc1e07e9',
    messagingSenderId: '15883659596',
    projectId: 'state-b9713',
    storageBucket: 'state-b9713.appspot.com',
    iosBundleId: 'com.example.app',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAchi_ambriwAhWAeVIf6aJ54_tAdPvvHs',
    appId: '1:15883659596:web:6241a91974ae015c1e07e9',
    messagingSenderId: '15883659596',
    projectId: 'state-b9713',
    authDomain: 'state-b9713.firebaseapp.com',
    storageBucket: 'state-b9713.appspot.com',
    measurementId: 'G-TV0DG4TSPF',
  );
}
